import '@idux/components/button/style/index.css';
import '@idux/components/checkbox/style/index.css';
import '@idux/components/empty/style/index.css';
import '@idux/components/header/style/index.css';
import '@idux/components/icon/style/index.css';
import '@idux/components/space/style/index.css';
import '@idux/components/spin/style/index.css';
import '@idux/components/style/core/reset.css';
import '@idux/components/tree/style/index.css';
